language: ruby
rvm:
  - 1.9.3

script:
  - rspec modules/framework/tests --format documentation --color

notifications:
  email:
    - niek.bartholomeus@gmail.com

branches:
  except:
    - /^v[0-9.]*/