language: ruby
rvm:
  - 1.9.3

before_install:
  - gem update --system 2.1.9

script:
  - bundle exec rspec tests --format documentation --color
  - rspec tests_no_bundler --format documentation --color

notifications:
  email:
    - niek.bartholomeus@gmail.com

branches:
  except:
    - /^v[0-9.]*/