language: ruby
rvm:
  - 1.9.3

before_install:
  - gem update --system 2.1.9

install: gem install brpm_module_brpm #needed for module installation tests

script:
  - rspec modules/framework/tests --format documentation --color

notifications:
  email:
    - niek.bartholomeus@gmail.com

branches:
  except:
    - /^v[0-9.]*/