language: ruby
rvm:
  - 1.9.3

script: bundle exec rspec ./modules/brpm/tests --format documentation
script: bundle exec rspec ./modules/bladelogic/tests --format documentation

notifications:
  email:
    - niek.bartholomeus@gmail.com