#!/usr/bin/env ruby
module_name = ENV["MODULE"]
automation_script_name = ARGV[0]
params_path = ARGV[1]
automation_type = ARGV[2]
parent_id = ARGV.size > 3 ? ARGV[3] : nil
offset = ARGV.size > 4 ? ARGV[4] : nil
max_records = ARGV.size > 5 ? ARGV[5] : nil

module_spec = Gem::Specification.find_by_name(module_name)
module_path = module_spec.gem_dir

gemfile_path = "#{module_path}/Gemfile"
if File.exists?(gemfile_path)
  ENV["BUNDLE_GEMFILE"] = gemfile_path
  require_bundler = "require 'bundler/setup';"
end

require 'brpm_script_executor'
BrpmScriptExecutor.execute_automation_script_from_other_process(module_name, automation_script_name, params_path, automation_type, parent_id, offset, max_records)
